# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Conchboards' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Conchboards
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'SwiftKeychainWrapper'
  pod 'Nuke'
  pod 'UIScrollView-InfiniteScroll', '~> 1.0.0'
  pod 'RxSwift', '~> 4.1'
  pod 'FontAwesome.swift' 
end
